-- MySQL Script generated by MySQL Workbench
-- Thu May 13 14:16:52 2021
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`all_gosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`all_gosts` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`10608-72`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`10608-72` (
  `id` INT NOT NULL,
  `m` VARCHAR(45) NULL,
  `s` VARCHAR(45) NULL,
  `all_gosts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `all_gosts_id`),
  INDEX `fk_10608-72_all_gosts_idx` (`all_gosts_id` ASC),
  CONSTRAINT `fk_10608-72_all_gosts`
    FOREIGN KEY (`all_gosts_id`)
    REFERENCES `mydb`.`all_gosts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rezb_10608-72`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rezb_10608-72` (
  `id` INT NOT NULL,
  `type_rezb` VARCHAR(45) NULL,
  `10608-72_id` INT NOT NULL,
  PRIMARY KEY (`id`, `10608-72_id`),
  INDEX `fk_rezb_10608-72_10608-721_idx` (`10608-72_id` ASC),
  CONSTRAINT `fk_rezb_10608-72_10608-721`
    FOREIGN KEY (`10608-72_id`)
    REFERENCES `mydb`.`10608-72` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
