-- MySQL Script generated by MySQL Workbench
-- Tue May  4 12:42:06 2021
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gosts` ;
USE `gosts` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`all_gosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gosts`.`all_gosts` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`10605-94`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gosts`.`10605-94` (
  `id` INT NOT NULL,
  `e` VARCHAR(45) NULL,
  `s` VARCHAR(45) NULL,
  `m` VARCHAR(45) NULL,
  `all_gosts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `all_gosts_id`),
  INDEX `fk_10605-94_all_gosts_idx` (`all_gosts_id` ASC),
  CONSTRAINT `fk_10605-94_all_gosts`
    FOREIGN KEY (`all_gosts_id`)
    REFERENCES `gosts`.`all_gosts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
